CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;


-- Table structure for table 'classification'
CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory
(
	inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	inv_make character varying NOT NULL,
	inv_model character varying NOT NULL,
	inv_year character(4) NOT NULL,
	inv_description text NOT NULL,
	inv_image character varying NOT NULL,
	inv_thumbnail character varying NOT NULL,
	inv_price numeric(9, 0) NOT NULL,
	inv_miles integer NOT NULL,
	inv_color character varying NOT NULL,
	classification_id integer NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Table: favorites
CREATE TABLE IF NOT EXISTS public.favorites
(
    favorite_id integer GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inv_id integer NOT NULL,
    favorite_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (favorite_id),
    CONSTRAINT fk_favorite_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorite_inventory
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON DELETE CASCADE,
    CONSTRAINT unique_favorite UNIQUE (account_id, inv_id)
);

-- Table structure for table 'reviews'
CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_id INT NOT NULL,
    account_id INT NULL,
    reviewer_name VARCHAR(100),
    review_rating INT NOT NULL CHECK (review_rating BETWEEN 1 AND 5),
    review_text TEXT NOT NULL,
    review_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
    -- Link review to vehicle
    CONSTRAINT fk_reviews_inventory
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON DELETE CASCADE,
    -- Optional link to account
    CONSTRAINT fk_reviews_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON DELETE SET NULL
);

-- Data for table 'classification'
INSERT INTO public.classification (classification_name)
VALUES ('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Data for table `inventory`
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
  )
VALUES   (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the car you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
  ), (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.',
    '/images/batmobile.jpg',
    '/images/batmobile-tn.jpg',
    65000,
    29887,
    'Black',
    1
  ), (
    'FBI',
    'Surveillance Van',
    '2016',
    'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.',
    '/images/survan.jpg',
    '/images/survan-tn.jpg',
    20000,
    19851,
    'Brown',
    1
  ), (
    'Dog',
    'Car',
    '1997',
    'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
    '/images/dog-car.jpg',
    '/images/dog-car-tn.jpg',
    35000,
    71632,
    'White',
    1
  ), (
    'Jeep',
    'Wrangler',
    '2019',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
    '/images/wrangler.jpg',
    '/images/wrangler-tn.jpg',
    28045,
    41205,
    'Yellow',
    3
  ), (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
    '/images/adventador.jpg',
    '/images/adventador-tn.jpg',
    417650,
    71003,
    'Blue',
    2
  ), (
    'Aerocar International',
    'Aerocar',
    '1963',
    'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
    '/images/aerocar.jpg',
    '/images/aerocar-tn.jpg',
    700000,
    18956,
    'Red',
    1
  ), (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
    '/images/monster-truck.jpg',
    '/images/monster-truck-tn.jpg',
    150000,
    3998,
    'purple',
    1
  ), (
    'Cadillac',
    'Escalade',
    '2019',
    'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
    '/images/escalade.jpg',
    '/images/escalade-tn.jpg',
    75195,
    41958,
    'Black',
    4
  ), (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
    '/images/hummer.jpg',
    '/images/hummer-tn.jpg',
    58800,
    56564,
    'Yellow',
    4
  ), (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car came from. however with a little tlc it will run as good a new.',
    '/images/mechanic.jpg',
    '/images/mechanic-tn.jpg',
    100,
    200125,
    'Rust',
    5
  ), (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
    '/images/model-t.jpg',
    '/images/model-t-tn.jpg',
    30000,
    26357,
    'Black',
    5
  ), (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
    '/images/mystery-van.jpg',
    '/images/mystery-van-tn.jpg',
    10000,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
    '/images/fire-truck.jpg',
    '/images/fire-truck-tn.jpg',
    50000,
    38522,
    'Red',
    4
  ), (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
    '/images/crwn-vic.jpg',
    '/images/crwn-vic-tn.jpg',
    10000,
    108247,
    'White',
    5
  );

  -- Table: reviews
INSERT INTO public.reviews
(inv_id, account_id, reviewer_name, review_rating, review_text, review_date)
VALUES
(1, NULL, 'SpeedLover', 5, 'This Camaro is incredibly fun and handles beautifully.', '2025-03-12 14:23:00'),
(1, NULL, 'DailyDriver', 4, 'Solid performance for the price.', '2025-04-08 09:41:00'),
(2, NULL, 'NightRider', 5, 'Feels like being in a movie every time I drive it.', '2025-05-16 21:12:00'),
(3, NULL, 'Watcher', 4, 'Great van with tons of space and tech.', '2025-06-01 18:33:00'),
(4, NULL, 'DogFan', 5, 'The dog car turns heads everywhere!', '2025-06-25 11:07:00'),
(5, NULL, 'TrailSeeker', 5, 'Best Jeep I have owned. Handles trails perfectly.', '2025-07-14 15:55:00'),
(6, NULL, 'SupercarDream', 5, 'Insanely fast and beautiful machine.', '2025-08-02 13:21:00'),
(7, NULL, 'PilotDriver', 4, 'Flying mode makes commuting easy!', '2025-08-19 10:45:00'),
(8, NULL, 'MudKing', 5, 'Monster truck is pure fun.', '2025-09-03 17:14:00'),
(9, NULL, 'LuxuryFan', 4, 'Very comfortable ride for the family.', '2025-09-28 19:02:00'),
(10, NULL, 'OffroadDad', 4, 'Great off-road performance.', '2025-10-10 08:37:00'),
(11, NULL, 'FixerUpper', 3, 'Needs work but worth restoring.', '2025-10-29 12:50:00'),
(12, NULL, 'HistoryBuff', 5, 'Amazing piece of automotive history.', '2025-11-11 16:28:00'),
(13, NULL, 'MysterySolver', 5, 'Perfect van for solving mysteries.', '2025-12-05 20:11:00'),
(14, NULL, 'FireHero', 5, 'Huge vehicle and impressive equipment.', '2025-12-22 07:56:00'),
(15, NULL, 'CopShowFan', 4, 'Fun car with plenty of character.', '2026-01-08 14:05:00'),
-- Logged-in account examples
(1, NULL, 'VerifiedOwner', 5, 'Owned it for a year, still love it.', '2026-01-19 18:42:00'),
(5, NULL, 'VerifiedOwner', 5, 'Perfect weekend adventure vehicle.', '2026-02-02 09:15:00');

-- #4 from Assignment 2 Task One ----------------------
-- Modify the "GM Hummer" record to read "a huge interior" rather than "small interiors" using a single query.
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- #6 from Assignment 2 Task One ----------------------
-- Update all records in the inventory table to add "/vehicles" to the middle of the file path in the inv_image and inv_thumbnail columns using a single query.
UPDATE public.inventory
SET
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');